services:

  fetcher:
    container_name: fetcher
    restart: on-failure
    env_file:
      - .env
    build:
      context: Docker/fetcher
      dockerfile: Dockerfile
    volumes:
      - ./images:/images
  
  retriever:
    container_name: retriever
    restart: on-failure
    env_file:
      - .env
    build:
      context: Docker/retriever
      dockerfile: Dockerfile
    volumes:
      - ${EXPORTED_PATH}:/app/exported
      - ./JSON_images:/json_images
  
  object-detector:
    container_name: object-detector
    restart: on-failure
    build:
      context: Docker/objectDetector
      dockerfile: Dockerfile
    volumes:
      - ./images:/images
      - ./results:/app/results
  
  dashboard:
    container_name: dashboard
    restart: on-failure
    build:
      context: Docker/dashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./images:/images
      - ./results:/app/results


